apiVersion: extensions/v1beta1
kind: Pod
metadata:
    labels:
    service: backend-feed
spec:
    containers:
        - image: mg4u/udacity-restapi-feed
    name: backend-feed
    imagePullPolicy: Always  
    resources:
        requests:
            memory: "64Mi"
            cpu: "250m"
        limits:
            memory: "1024Mi"
            cpu: "500m"                  
    env:
    - name: URL
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: URL
    - name: AWS_BUCKET
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: AWS_BUCKET
    - name: AWS_PROFILE
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: AWS_PROFILE
    - name: AWS_REGION
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: AWS_REGION
    - name: URL
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: URL 
    - name: HOST
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: HOST
    - name: DB_ENGING
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: DB_ENGING
    - name: DB_HOST
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: DB_HOST
    - name: DB_NAME
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: DB_NAME

    - name: DB_USERNAME
        valueFrom:
        secretKeyRef:
            name: env-secret
            key: DB_USERNAME
    - name: DB_PASSWORD
        valueFrom:
        secretKeyRef:
            name: env-secret
            key: DB_PASSWORD

    - name: jwttoken
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: jwttoken
    - name: APITOKEN
        valueFrom:
        configMapKeyRef:
            name: env-config
            key: APITOKEN


    volumeMounts:
    - name: aws-secret
        mountPath: "/root/.aws/"
        readOnly: true        
    restartPolicy: Always
    volumes:
    - name: aws-secret
    secret:
        secretName: aws-secret