version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mg4u/reverseproxy 
  backend_user:
    build:
      context: ../user-service
    image: mg4u/udacity-restapi-user
  backend_user:
    build:
      context: ../user-service
    image: mg4u/udacity-restapi-user
  frontend:
    build:
      context: ../udacity-c3-frontend  
    image: mg4u/udacity-frontend:local
  